---
- name: Loops Playbook
  hosts: linux1
  become: yes

  tasks: 
  - name: Say hello to all
    debug: msg="Hello {{ item }}"
    loop:
        - "1"
        - "2" 
        - "3" 
        - "4" 

  - name: Loop until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt 
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZ") == false

  - name: Print
    debug:
      var: output
