---
- name: Ansible lesson 19
  hosts: all
  any_errors_fatal: true
  become: yes

  tasks:
  - name: Task 1
    yum: name=treeee state=latest
    ignore_errors: yes

  - name: Task 2
    shell: echo Hello World!
    register: results
    # failed_when: results.rc == 0
    # failed_when: "'World' in results.stdout"

  - debug:
      var: results

  - name: Task 3
    shell: cat /home/user/test.txt
    register: results1

  - name: Task 4
    shell: cat /home/user/test.txt
