---
- name: My include playbook
  hosts: all
  become: yes

  vars:
   mytext: "Hello from ADV"

  tasks:
  - name: Ping test
    ping:

  - name: Create Folders
    include: create_folders.yml

  - name: Create Files
    include: create_files.yml mytext="Hello from now"
